/**
 * vowelBoard.ts — spatial state for Lab 02 simple-vowel cards.
 *
 * Hangul's ten simple vowels are still generated by `buildVowel`. This module
 * is the dock geometry and stamp rules the learner operates: which docks exist,
 * which stamps they accept, and where a drop snaps.
 */
import { buildVowel, sidesFor, type TickSide } from './hangul';

export type Stamp = 'ㅣ' | 'ㅡ' | 'tick';
export type BaseStroke = 'ㅣ' | 'ㅡ';
export type DockId = 'base' | TickSide | `${TickSide}2`;

export interface BoardState {
	base: BaseStroke | null;
	ticks: 0 | 1 | 2;
	side: TickSide | null;
}

export interface Lift {
	stamp: Stamp;
	/** 2 only when the iotation stack is lifted from a primary tick dock. */
	count: 1 | 2;
}

export const EMPTY_BOARD: BoardState = { base: null, ticks: 0, side: null };

export const PALETTE: readonly Stamp[] = ['ㅣ', 'ㅡ', 'tick'];

export const SNAP_RADIUS_RATIO = 0.2;
export const SNAP_RADIUS_MIN_PX = 44;

export function dockPosition(id: DockId): { x: number; y: number } {
	switch (id) {
		case 'base':
			return { x: 0.5, y: 0.5 };
		case 'left':
			return { x: 0.22, y: 0.5 };
		case 'left2':
			return { x: 0.08, y: 0.5 };
		case 'right':
			return { x: 0.78, y: 0.5 };
		case 'right2':
			return { x: 0.92, y: 0.5 };
		case 'above':
			return { x: 0.5, y: 0.22 };
		case 'above2':
			return { x: 0.5, y: 0.08 };
		case 'below':
			return { x: 0.5, y: 0.78 };
		case 'below2':
			return { x: 0.5, y: 0.92 };
		default: {
			const _exhaustive: never = id;
			return _exhaustive;
		}
	}
}

export function sideOfDock(id: DockId): TickSide | null {
	switch (id) {
		case 'base':
			return null;
		case 'left':
		case 'left2':
			return 'left';
		case 'right':
		case 'right2':
			return 'right';
		case 'above':
		case 'above2':
			return 'above';
		case 'below':
		case 'below2':
			return 'below';
		default: {
			const _exhaustive: never = id;
			return _exhaustive;
		}
	}
}

export function isSecondaryDock(id: DockId): boolean {
	return id !== 'base' && id.endsWith('2');
}

export function visibleDocks(state: BoardState): DockId[] {
	if (!state.base) return ['base'];
	const primaries = sidesFor(state.base);
	const docks: DockId[] = ['base', ...primaries];
	if (state.ticks >= 1 && state.side && primaries.includes(state.side)) {
		docks.push(`${state.side}2`);
	}
	return docks;
}

export function occupant(state: BoardState, dock: DockId): Stamp | null {
	if (dock === 'base') return state.base;
	const side = sideOfDock(dock);
	if (!side || state.side !== side) return null;
	if (isSecondaryDock(dock)) return state.ticks === 2 ? 'tick' : null;
	return state.ticks >= 1 ? 'tick' : null;
}

export function applyLift(state: BoardState, dock: DockId, lift: Lift): BoardState | null {
	switch (lift.stamp) {
		case 'tick': {
			if (!state.base || dock === 'base') return null;
			const side = sideOfDock(dock);
			if (!side || !sidesFor(state.base).includes(side)) return null;
			if (!visibleDocks(state).includes(dock)) return null;
			if (isSecondaryDock(dock)) return { ...state, side, ticks: 2 };
			const ticks = Math.max(lift.count, state.ticks, 1) as 1 | 2;
			return { ...state, side, ticks };
		}
		case 'ㅣ':
		case 'ㅡ': {
			if (dock !== 'base' || lift.count !== 1) return null;
			if (state.base === lift.stamp) return state;
			return { base: lift.stamp, ticks: 0, side: null };
		}
		default: {
			const _exhaustive: never = lift.stamp;
			return _exhaustive;
		}
	}
}

export function applyStamp(state: BoardState, dock: DockId, stamp: Stamp): BoardState | null {
	return applyLift(state, dock, { stamp, count: 1 });
}

/** Stamps that would seat on this dock, in palette order. */
export function compatibleStamps(state: BoardState, dock: DockId): Stamp[] {
	return PALETTE.filter((stamp) => applyStamp(state, dock, stamp) !== null);
}

export function clearDock(state: BoardState, dock: DockId): BoardState {
	if (dock === 'base') return EMPTY_BOARD;
	const side = sideOfDock(dock);
	if (state.side !== side) return state;
	if (isSecondaryDock(dock)) {
		if (state.ticks === 2) return { ...state, ticks: 1 };
		return state;
	}
	if (state.ticks >= 1) return { ...state, ticks: 0, side: null };
	return state;
}

export function liftDock(
	state: BoardState,
	dock: DockId
): { lift: Lift; remaining: BoardState } | null {
	const piece = occupant(state, dock);
	if (!piece) return null;
	const remaining = clearDock(state, dock);
	if (piece === 'tick' && !isSecondaryDock(dock) && state.ticks === 2) {
		return { lift: { stamp: 'tick', count: 2 }, remaining };
	}
	return { lift: { stamp: piece, count: 1 }, remaining };
}

export function vowelOf(state: BoardState): string {
	if (!state.base) return '';
	return buildVowel(state.base, state.side, state.ticks);
}

export function snapRadiusPx(boardSizePx: number): number {
	return Math.max(SNAP_RADIUS_RATIO * boardSizePx, SNAP_RADIUS_MIN_PX);
}

export function snapDock(
	state: BoardState,
	lift: Lift,
	x: number,
	y: number,
	boardSizePx: number
): DockId | null {
	const radius = snapRadiusPx(boardSizePx);
	let best: DockId | null = null;
	let bestDist = Infinity;
	for (const id of visibleDocks(state)) {
		if (applyLift(state, id, lift) === null) continue;
		const pos = dockPosition(id);
		const dx = pos.x * boardSizePx - x;
		const dy = pos.y * boardSizePx - y;
		const dist = Math.hypot(dx, dy);
		if (dist <= radius && dist < bestDist) {
			best = id;
			bestDist = dist;
		}
	}
	return best;
}

export function stampLabel(stamp: Stamp): string {
	switch (stamp) {
		case 'ㅣ':
			return 'standing stroke';
		case 'ㅡ':
			return 'earth stroke';
		case 'tick':
			return 'tick';
		default: {
			const _exhaustive: never = stamp;
			return _exhaustive;
		}
	}
}
