/**
 * vowelBoard.ts — spatial state for Lab 02 simple-vowel cards.
 *
 * Hangul's ten simple vowels are still generated by `buildVowel`. This module
 * is the dock geometry and stamp rules the learner operates: which docks exist,
 * which stamps they accept, and where a drop snaps.
 */
import { buildVowel, sidesFor, type TickSide } from './hangul';

export type Stamp = 'ㅣ' | 'ㅡ' | 'tick';
export type BaseStroke = 'ㅣ' | 'ㅡ';
export type DockId = 'base' | TickSide | `${TickSide}2`;
export type DockDir = 'left' | 'right' | 'up' | 'down';

export interface BoardState {
	base: BaseStroke | null;
	ticks: 0 | 1 | 2;
	side: TickSide | null;
}

export interface Lift {
	stamp: Stamp;
	/** 2 only when the iotation stack is lifted from a primary tick dock. */
	count: 1 | 2;
}

export const EMPTY_BOARD: BoardState = { base: null, ticks: 0, side: null };

export const PALETTE: readonly Stamp[] = ['ㅣ', 'ㅡ', 'tick'];

export const SNAP_RADIUS_RATIO = 0.2;
export const SNAP_RADIUS_MIN_PX = 44;

export function dockPosition(id: DockId): { x: number; y: number } {
	switch (id) {
		case 'base':
			return { x: 0.5, y: 0.5 };
		case 'left':
			return { x: 0.22, y: 0.5 };
		case 'left2':
			return { x: 0.08, y: 0.5 };
		case 'right':
			return { x: 0.78, y: 0.5 };
		case 'right2':
			return { x: 0.92, y: 0.5 };
		case 'above':
			return { x: 0.5, y: 0.22 };
		case 'above2':
			return { x: 0.5, y: 0.08 };
		case 'below':
			return { x: 0.5, y: 0.78 };
		case 'below2':
			return { x: 0.5, y: 0.92 };
		default: {
			const _exhaustive: never = id;
			return _exhaustive;
		}
	}
}

export function sideOfDock(id: DockId): TickSide | null {
	switch (id) {
		case 'base':
			return null;
		case 'left':
		case 'left2':
			return 'left';
		case 'right':
		case 'right2':
			return 'right';
		case 'above':
		case 'above2':
			return 'above';
		case 'below':
		case 'below2':
			return 'below';
		default: {
			const _exhaustive: never = id;
			return _exhaustive;
		}
	}
}

export function isSecondaryDock(id: DockId): boolean {
	return id !== 'base' && id.endsWith('2');
}

function neighborDock(from: DockId, direction: DockDir): DockId | null {
	switch (from) {
		case 'base':
			switch (direction) {
				case 'left':
					return 'left';
				case 'right':
					return 'right';
				case 'up':
					return 'above';
				case 'down':
					return 'below';
				default: {
					const _exhaustive: never = direction;
					return _exhaustive;
				}
			}
		case 'left':
			switch (direction) {
				case 'left':
					return 'left2';
				case 'right':
					return 'base';
				case 'up':
				case 'down':
					return null;
				default: {
					const _exhaustive: never = direction;
					return _exhaustive;
				}
			}
		case 'left2':
			switch (direction) {
				case 'right':
					return 'left';
				case 'left':
				case 'up':
				case 'down':
					return null;
				default: {
					const _exhaustive: never = direction;
					return _exhaustive;
				}
			}
		case 'right':
			switch (direction) {
				case 'left':
					return 'base';
				case 'right':
					return 'right2';
				case 'up':
				case 'down':
					return null;
				default: {
					const _exhaustive: never = direction;
					return _exhaustive;
				}
			}
		case 'right2':
			switch (direction) {
				case 'left':
					return 'right';
				case 'right':
				case 'up':
				case 'down':
					return null;
				default: {
					const _exhaustive: never = direction;
					return _exhaustive;
				}
			}
		case 'above':
			switch (direction) {
				case 'up':
					return 'above2';
				case 'down':
					return 'base';
				case 'left':
				case 'right':
					return null;
				default: {
					const _exhaustive: never = direction;
					return _exhaustive;
				}
			}
		case 'above2':
			switch (direction) {
				case 'down':
					return 'above';
				case 'up':
				case 'left':
				case 'right':
					return null;
				default: {
					const _exhaustive: never = direction;
					return _exhaustive;
				}
			}
		case 'below':
			switch (direction) {
				case 'up':
					return 'base';
				case 'down':
					return 'below2';
				case 'left':
				case 'right':
					return null;
				default: {
					const _exhaustive: never = direction;
					return _exhaustive;
				}
			}
		case 'below2':
			switch (direction) {
				case 'up':
					return 'below';
				case 'down':
				case 'left':
				case 'right':
					return null;
				default: {
					const _exhaustive: never = direction;
					return _exhaustive;
				}
			}
		default: {
			const _exhaustive: never = from;
			return _exhaustive;
		}
	}
}

/** Next visible dock in a compass direction. Does not wrap. */
export function dockInDirection(
	state: BoardState,
	from: DockId,
	direction: DockDir,
	docks: readonly DockId[] = visibleDocks(state)
): DockId {
	const next = neighborDock(from, direction);
	if (!next) return from;
	return docks.includes(next) ? next : from;
}

export function visibleDocks(state: BoardState): DockId[] {
	if (!state.base) return ['base'];
	const primaries = sidesFor(state.base);
	const docks: DockId[] = ['base', ...primaries];
	if (state.ticks >= 1 && state.side && primaries.includes(state.side)) {
		docks.push(`${state.side}2`);
	}
	return docks;
}

/** Invert a simple vowel into the stamps that build it. */
export function recipeOf(vowel: string): BoardState | null {
	const bases: BaseStroke[] = ['ㅣ', 'ㅡ'];
	for (const base of bases) {
		if (vowel === base) return { base, ticks: 0, side: null };
		for (const side of sidesFor(base)) {
			if (buildVowel(base, side, 1) === vowel) return { base, ticks: 1, side };
			if (buildVowel(base, side, 2) === vowel) return { base, ticks: 2, side };
		}
	}
	return null;
}

/** Docks required to construct `target`, in seating order. */
export function recipeDocks(vowel: string): DockId[] {
	const recipe = recipeOf(vowel);
	if (!recipe?.base) return ['base'];
	const docks: DockId[] = ['base'];
	if (recipe.ticks >= 1 && recipe.side) docks.push(recipe.side);
	if (recipe.ticks === 2 && recipe.side) docks.push(`${recipe.side}2`);
	return docks;
}

/**
 * Empty recipe docks still needed for `target`. Complete letters have none:
 * remaining placeholders are n − m, where n is recipe length and m is how
 * many of those docks already hold their piece.
 */
export function placeholderDocks(state: BoardState, target: string): DockId[] {
	if (vowelOf(state) === target) return [];
	return recipeDocks(target).filter((id) => occupant(state, id) === null);
}

/** Interactive docks: remaining placeholders plus occupied magnets. None on a win. */
export function boardDocks(state: BoardState, target: string): DockId[] {
	if (vowelOf(state) === target) return [];
	const shown = new Set<DockId>(placeholderDocks(state, target));
	for (const id of visibleDocks(state)) {
		if (occupant(state, id)) shown.add(id);
	}
	const ordered: DockId[] = [];
	for (const id of recipeDocks(target)) {
		if (shown.has(id)) ordered.push(id);
	}
	for (const id of visibleDocks(state)) {
		if (shown.has(id) && !ordered.includes(id)) ordered.push(id);
	}
	return ordered;
}

/** True when the board is a correct prefix of `target` (incomplete, not wrong). */
export function towardTarget(state: BoardState, target: string): boolean {
	const recipe = recipeOf(target);
	if (!recipe?.base || !state.base) return false;
	if (state.base !== recipe.base) return false;
	if (recipe.ticks === 0) return state.ticks === 0;
	if (state.ticks === 0) return true;
	if (state.side !== recipe.side) return false;
	return state.ticks <= recipe.ticks;
}

export function occupant(state: BoardState, dock: DockId): Stamp | null {
	if (dock === 'base') return state.base;
	const side = sideOfDock(dock);
	if (!side || state.side !== side) return null;
	if (isSecondaryDock(dock)) return state.ticks === 2 ? 'tick' : null;
	return state.ticks >= 1 ? 'tick' : null;
}

export function applyLift(state: BoardState, dock: DockId, lift: Lift): BoardState | null {
	switch (lift.stamp) {
		case 'tick': {
			if (!state.base || dock === 'base') return null;
			const side = sideOfDock(dock);
			if (!side || !sidesFor(state.base).includes(side)) return null;
			if (!visibleDocks(state).includes(dock)) return null;
			if (isSecondaryDock(dock)) return { ...state, side, ticks: 2 };
			const ticks = Math.max(lift.count, state.ticks, 1) as 1 | 2;
			return { ...state, side, ticks };
		}
		case 'ㅣ':
		case 'ㅡ': {
			if (dock !== 'base' || lift.count !== 1) return null;
			if (state.base === lift.stamp) return state;
			return { base: lift.stamp, ticks: 0, side: null };
		}
		default: {
			const _exhaustive: never = lift.stamp;
			return _exhaustive;
		}
	}
}

export function applyStamp(state: BoardState, dock: DockId, stamp: Stamp): BoardState | null {
	return applyLift(state, dock, { stamp, count: 1 });
}

/** Stamps that would seat on this dock, in palette order. */
export function compatibleStamps(state: BoardState, dock: DockId): Stamp[] {
	return PALETTE.filter((stamp) => applyStamp(state, dock, stamp) !== null);
}

export function clearDock(state: BoardState, dock: DockId): BoardState {
	if (dock === 'base') return EMPTY_BOARD;
	const side = sideOfDock(dock);
	if (state.side !== side) return state;
	if (isSecondaryDock(dock)) {
		if (state.ticks === 2) return { ...state, ticks: 1 };
		return state;
	}
	if (state.ticks >= 1) return { ...state, ticks: 0, side: null };
	return state;
}

export function liftDock(
	state: BoardState,
	dock: DockId
): { lift: Lift; remaining: BoardState } | null {
	const piece = occupant(state, dock);
	if (!piece) return null;
	const remaining = clearDock(state, dock);
	if (piece === 'tick' && !isSecondaryDock(dock) && state.ticks === 2) {
		return { lift: { stamp: 'tick', count: 2 }, remaining };
	}
	return { lift: { stamp: piece, count: 1 }, remaining };
}

export function vowelOf(state: BoardState): string {
	if (!state.base) return '';
	return buildVowel(state.base, state.side, state.ticks);
}

export function snapRadiusPx(boardSizePx: number): number {
	return Math.max(SNAP_RADIUS_RATIO * boardSizePx, SNAP_RADIUS_MIN_PX);
}

export function snapDock(
	state: BoardState,
	lift: Lift,
	x: number,
	y: number,
	boardSizePx: number,
	docks: readonly DockId[] = visibleDocks(state)
): DockId | null {
	const radius = snapRadiusPx(boardSizePx);
	let best: DockId | null = null;
	let bestDist = Infinity;
	for (const id of docks) {
		if (applyLift(state, id, lift) === null) continue;
		const pos = dockPosition(id);
		const dx = pos.x * boardSizePx - x;
		const dy = pos.y * boardSizePx - y;
		const dist = Math.hypot(dx, dy);
		if (dist <= radius && dist < bestDist) {
			best = id;
			bestDist = dist;
		}
	}
	return best;
}

export function stampLabel(stamp: Stamp): string {
	switch (stamp) {
		case 'ㅣ':
			return 'standing stroke';
		case 'ㅡ':
			return 'earth stroke';
		case 'tick':
			return 'tick';
		default: {
			const _exhaustive: never = stamp;
			return _exhaustive;
		}
	}
}
