/**
 * Which letter clips actually exist under `static/audio/` — the
 * recording-availability gate read by `letters.ts`.
 *
 * AUTO-GENERATED by `app/scripts/ingest-recordings.mjs`. Do not edit by hand:
 * ingest (or re-sync) recordings and let the script rewrite this file.
 *
 * Entries are `<dir>/<slug>` (e.g. `consonants/g`, `vowels/a`, `finals/k`),
 * and each entry promises that both `<slug>.opus` and `<slug>.mp3` are on
 * disk. Empty until Sally's native-speaker recordings are ingested — see
 * docs/recording/sally-runbook.md.
 */
export const RECORDED: ReadonlySet<string> = new Set([]);
